/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS Local Storage API
 * <picture>     <source media=\"(prefers-color-scheme: dark)\" srcset=\"https://raw.githubusercontent.com/IceWhaleTech/logo/main/casaos/casaos_banner_dark_night_800px.png\">     <source media=\"(prefers-color-scheme: light)\" srcset=\"https://raw.githubusercontent.com/IceWhaleTech/logo/main/casaos/casaos_banner_twilight_blue_800px.png\">     <img alt=\"CasaOS\" src=\"https://raw.githubusercontent.com/IceWhaleTech/logo/main/casaos/casaos_banner_twilight_blue_800px.png\"> </picture>  CasaOS Local Storage service manages local storage including disks, partitions and mounting points.  This API allows interacting with the service to conduct such management.  For issues and discussions, please visit the [GitHub repository](https://github.com/IceWhaleTech/CasaOS) or join [our Discord](https://discord.gg/knqAbbBbeX).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Mount
 */
export interface Mount {
    /**
     * 
     * @type {number}
     * @memberof Mount
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Mount
     */
    'mount_point': string;
    /**
     * 
     * @type {string}
     * @memberof Mount
     */
    'fstype'?: string;
    /**
     * 
     * @type {string}
     * @memberof Mount
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof Mount
     */
    'options'?: string;
    /**
     * `true` if the mount should be persisted in `/etc/fstab`, `false` otherwise
     * @type {boolean}
     * @memberof Mount
     */
    'persist'?: boolean;
    /**
     * Extended properties of the mount
     * @type {{ [key: string]: string; }}
     * @memberof Mount
     */
    'extended'?: { [key: string]: string; };
}

